name: CI for Docker Image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Create Image
          uses: docker/build-push-action@v6
          with:
            context: .
            tags: ${{ secrets.DOCKER_USERNAME }}/win-dev-env:latest

        - name: Run Docker container
          run: docker run --rm -v "$(pwd):C:\dev" -w C:\dev ${{ secrets.DOCKER_USERNAME }}/win-dev-env:latest ./scripts/create-manifest.ps1 -OutputPath ./manifests.md

        - name: Build
          run: docker run --rm -v "$(pwd):C:\dev" -w C:\dev ${{ secrets.DOCKER_USERNAME }}/win-dev-env:latest cmake -S . -B build; cmake --build build; ctest --test-dir build -C Release

        - name: Push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
            tags: ${{ secrets.DOCKER_USERNAME }}/win-dev-env:latest